// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerEntityDataWCF.Model;

namespace ServerEntityDataWCF.Migrations
{
    [DbContext(typeof(ModelContext))]
    partial class ModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ServerEntityDataWCF.Model.ArchiveFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int>("UserCloudId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("UserCloudId");

                    b.ToTable("ArchiveFiles");
                });

            modelBuilder.Entity("ServerEntityDataWCF.Model.IFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Folders");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IFolder");
                });

            modelBuilder.Entity("ServerEntityDataWCF.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ServerEntityDataWCF.Model.ArchiveFolder", b =>
                {
                    b.HasBaseType("ServerEntityDataWCF.Model.IFolder");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasIndex("ParentId");

                    b.HasDiscriminator().HasValue("ArchiveFolder");
                });

            modelBuilder.Entity("ServerEntityDataWCF.Model.UserCloud", b =>
                {
                    b.HasBaseType("ServerEntityDataWCF.Model.IFolder");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("UserCloud");
                });

            modelBuilder.Entity("ServerEntityDataWCF.Model.ArchiveFile", b =>
                {
                    b.HasOne("ServerEntityDataWCF.Model.IFolder", "ParentFolder")
                        .WithMany("Files")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServerEntityDataWCF.Model.UserCloud", "UserCloud")
                        .WithMany()
                        .HasForeignKey("UserCloudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServerEntityDataWCF.Model.ArchiveFolder", b =>
                {
                    b.HasOne("ServerEntityDataWCF.Model.IFolder", "ParentFolder")
                        .WithMany("Folders")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServerEntityDataWCF.Model.UserCloud", b =>
                {
                    b.HasOne("ServerEntityDataWCF.Model.User", "User")
                        .WithOne("UserCloud")
                        .HasForeignKey("ServerEntityDataWCF.Model.UserCloud", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
